### ISSUE TITLE
セーブデータのロードでエラー出る

### ISSUE THREAD

**Issue by sirokuma2020** [nikachu2012/Sirokuma-Clicker-V2#11]
去年からあったっぽい

**Comment by nikachu2012** [comment]
どんなエラー？

**Comment by sirokuma2020** [comment]
![image](https://github.com/user-attachments/assets/68dd114a-7c88-4ba3-8516-e5720232e8c9)
![image](https://github.com/user-attachments/assets/e69465e5-bf7f-4f3a-911e-63597a888f28)
こんな感じ
